name: sohmkapila
favicon: null
layout_spectrum: 0.79772
typography_spectrum: 0.40238
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000302'
    - '#44635c'
    - '#ffebdb'
    - '#bc7154'
    - '#acaba7'
  brandStrength: 0.418538712663576
  lightness: 0.987303132424131
  saturation: 0.8564233512151986
  rhythmicContrast: 0.5428268029354513
purpose: []
